# permissions for end users to view servicelevels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: servicelevel-viewer-role
rules:
- apiGroups:
  - monitoring.aminasian.com
  resources:
  - servicelevels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.aminasian.com
  resources:
  - servicelevels/status
  verbs:
  - get
