name: Build and Publish New Container Image
#on:
#  push:
#    tags:
#      - '*.*.*'
on:
  - push
jobs:
  build:
    name: Build and Publish Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set Git Version Env Variable
        run: export VERSION=$(git describe --tags --abbrev=0)
      - name: Build Container
        run: make docker-build IMG=aminasian/prometheus-slo-operator:${VERSION}
      - name: Publish Container
        run: make docker-push IMG=aminasian/prometheus-slo-operator:${VERSION}